### PR TITLE
Fix typo "unest" and update variable ref

### PR DESCRIPTION
**Pull request by FraiFish**
This is all I'm good for. fixing typos

### CODE REVIEW

**Comment by geckro** [comment]
Did you test before making the pull request that it did not screw anything up?

**Review by geckro — CHANGES_REQUESTED** [review]
tested?

**Review by FraiFish — COMMENTED** [review]
i have tested it now

**Comment by FraiFish** [comment]
second commit: you had a variable reference called --background-color and it doesnt actually exist and your other background colors are using the --page-color variable so i corrected that one

**Pull request merged**
